### PR TITLE
fix: return up to `model.MaxMappingInventoryAttributes` attributes

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: None
Ticket: None

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Review by mzedel — CHANGES_REQUESTED** [review]
This once again doesn't address the underlying issue (somehow you can have more attributes to index than the limit should allow) but masks it.

**Comment by tranchitella** [comment]
> This once again doesn't address the underlying issue (somehow you can have more attributes to index than the limit should allow) but masks it.

@mzedel there are reasons why we need to limit the mapping when reading it, but still letting more attributes stored in the database. The main reason is that this optimizes the look up and the update of the mapping with a single atomic operation in the database, at the price of storing a few extra strings in the database that we'll ignore. There is a similar limit in the code paths that use the mapping.

**Comment by mzedel** [comment]
You could just limit the attribute list on write and be done. The list of attributes will certainly be read more often than updated.

**Comment by mzedel** [comment]
Once you reached 100 different attributes you won't have to do the write... And until then both calls should still be reasonably quick I suppose... If it's not this will likely not work with a proper number of tenants

**Comment by tranchitella** [comment]
@mzedel it's two round-trips to MongoDB vs one.
Please note that we do not expect many tenants to reach the 100, so it will be two queries almost all of the times.
As the mapping update is not controlled by the customer via API calls, but it is part of the indexing tasks which the backend process asynchronously, what's really the purpose of writing 100 entries to the DB instead of writing more and ignoring the ones above the threshold?

**Review by kjaskiewiczz — APPROVED** [review]
With this change user will get right information about the usage and limit.
Allocating more space or storing more information than visible to the user is a common practice IMO, and I guess it's always related to some implementation details (as it is in our case).
I understand the purpose of it, and I believe it's very nice and smart optimization.

**Pull request merged**
